### PR TITLE
Add support for non-AMD.

### PR DESCRIPTION
**Pull request by jgerigmeyer**
I'd like to use this in a project without browserify or an AMD structure. Is there a reason not to support this use case?

Thanks!

### CODE REVIEW

**Comment by jonathanong** [comment]
can you:

- [ ] move the UMD code to the end of the file
- [ ] don't indent the main body of the code (pretend the UMD wrapping isn't there)

**Comment by jgerigmeyer** [comment]
@jonathanong Like so?

**Comment by jonathanong** [comment]
i don't understand how meteor packages are defined.

**Comment by jonathanong** [comment]
thanks file:///Users/jong/Workspace/jonathanong/textarea-caret-position/test/index.html

**Pull request closed without merging**
